/**
 * Emoji suggestions for a countdown title, in all 11 app languages.
 *
 * Two layers, both read from public/emoji/ (shared with the native
 * EmojiSuggestionEngine.swift used by Siri/Shortcuts, so keep the two in sync):
 *  1. keywords.json — hand-made event-word map ("løn" → 💰, "umzug" → 📦).
 *     Emoji datasets describe what an emoji looks like, not which event it fits,
 *     so this is what catches most countdown titles.
 *  2. <lang>.json — emojibase labels + tags (generated by scripts/build-emoji-data.mjs).
 *
 * Data is fetched once per language; until it arrives suggestions are empty and
 * callers fall back to their defaults.
 */
import { useEffect, useMemo, useState } from 'react';
import i18n from 'i18next';
import { Capacitor, registerPlugin } from '@capacitor/core';

export interface EmojiResult {
  unicode: string;
  label: string;
}

type KeywordRow = [string, Record<string, string[]>];
type DataRow = [string, string, string[]]; // unicode, label, tags
interface DatasetIndex {
  tokens: Map<string, { unicode: string; label: string; order: number }[]>;
}

const LANGS = ['en', 'es', 'it', 'pt', 'de', 'ru', 'fr', 'da', 'sv', 'no', 'fi'];

// Function words and generic time words that match hundreds of emoji labels
// ("to" → Tonga flag, "day" → sun, "date" → kissing faces).
const STOPWORDS = new Set([
  'the', 'and', 'for', 'with', 'from', 'our', 'your', 'day', 'days', 'date', 'time', 'next', 'first', 'last', 'week', 'year',
  'los', 'las', 'del', 'con', 'para', 'por', 'una', 'dia',
  'della', 'con', 'per', 'una', 'giorno',
  'das', 'dos', 'com', 'para', 'uma',
  'der', 'die', 'das', 'und', 'mit', 'von', 'zum', 'zur', 'ein', 'eine', 'tag',
  'для', 'это', 'день',
  'les', 'des', 'une', 'pour', 'avec', 'jour',
  'og', 'med', 'til', 'fra', 'den', 'det', 'dag', 'min', 'mit', 'vores', 'hos',
  'och', 'med', 'till', 'fran', 'min', 'mitt', 'hos',
  'og', 'til', 'fra', 'hos',
  'ja', 'kanssa', 'paiva',
]);

export function normalize(str: string): string {
  return str.normalize('NFD').replace(/\p{Mn}/gu, '').toLowerCase();
}

function words(str: string): string[] {
  return normalize(str).split(/[^\p{L}\p{N}]+/u).filter(Boolean);
}

export function appLanguage(): string {
  const raw = (i18n.language || 'en').toLowerCase().slice(0, 2);
  const lang = raw === 'nb' || raw === 'nn' ? 'no' : raw;
  return LANGS.includes(lang) ? lang : 'en';
}

// --- data loading -----------------------------------------------------------

let keywords: { emoji: string; lang: string; kw: string; phrase: boolean }[] | null = null;
const datasets = new Map<string, DatasetIndex>();
const pending = new Map<string, Promise<void>>();
const listeners = new Set<() => void>();

async function fetchJson<T>(file: string): Promise<T> {
  const res = await fetch(`${import.meta.env?.BASE_URL ?? '/'}emoji/${file}`);
  if (!res.ok) throw new Error(`emoji data ${file}: ${res.status}`);
  return res.json();
}

function once(key: string, load: () => Promise<void>): Promise<void> {
  if (!pending.has(key)) {
    pending.set(
      key,
      load()
        .then(() => listeners.forEach((l) => l()))
        .catch((err) => {
          pending.delete(key); // allow a retry on the next call
          console.warn('[emojiSuggestions]', err);
        }),
    );
  }
  return pending.get(key)!;
}

export function loadEmojiData(lang = appLanguage()): Promise<void> {
  const kw = once('keywords', async () => {
    const rows = await fetchJson<KeywordRow[]>('keywords.json');
    keywords = rows.flatMap(([emoji, byLang]) =>
      Object.entries(byLang).flatMap(([l, list]) =>
        list.map((w) => {
          const kw = words(w).join(' ');
          return { emoji, lang: l, kw, phrase: kw.includes(' ') };
        }),
      ),
    );
  });
  const data = [...new Set([lang, 'en'])].map((l) =>
    once(`data:${l}`, async () => {
      const rows = await fetchJson<DataRow[]>(`${l}.json`);
      const tokens: DatasetIndex['tokens'] = new Map();
      rows.forEach(([unicode, label, tags], order) => {
        for (const w of new Set([label, ...tags].flatMap(words))) {
          if (!tokens.has(w)) tokens.set(w, []);
          tokens.get(w)!.push({ unicode, label, order });
        }
      });
      datasets.set(l, { tokens });
    }),
  );
  return Promise.all([kw, ...data]).then(() => undefined);
}

if (typeof window !== 'undefined') {
  void loadEmojiData();
  i18n.on?.('languageChanged', () => void loadEmojiData());
}

// --- matching ---------------------------------------------------------------

/** Event-word map. Same-language matches outrank words from other languages. */
function keywordScores(titleWords: string[], lang: string): Map<string, number> {
  const scores = new Map<string, number>();
  if (!keywords) return scores;
  const joined = ` ${titleWords.join(' ')} `;
  const bump = (emoji: string, s: number) => scores.set(emoji, Math.max(scores.get(emoji) ?? 0, s));

  for (const { emoji, lang: l, kw, phrase } of keywords) {
    const same = l === lang;
    const len = kw.length;
    if (!same && len < 4) continue; // "em" (pt: "in") must not hit German "EM" ⚽
    if (phrase) {
      if (joined.includes(` ${kw} `)) bump(emoji, (same ? 1000 : 500) + len);
      continue;
    }
    for (const w of titleWords) {
      if (w === kw) bump(emoji, (same ? 1000 : 500) + len);
      // Compounds ("sommerferie", "fodboldkamp"), same language only:
      // ≥5 letters anywhere, 4 letters only as the compound's head (suffix).
      else if (same && ((len >= 5 && w.includes(kw)) || (len === 4 && w.endsWith(kw)))) bump(emoji, 700 + len);
    }
  }
  return scores;
}

function datasetResults(titleWords: string[], index: DatasetIndex | undefined): EmojiResult[] {
  if (!index) return [];
  const scored = new Map<string, { label: string; order: number; score: number }>();
  const add = (e: { unicode: string; label: string; order: number }, s: number) => {
    const cur = scored.get(e.unicode);
    if (cur) cur.score += s;
    else scored.set(e.unicode, { label: e.label, order: e.order, score: s });
  };
  for (const q of titleWords) {
    if (q.length < 3 || STOPWORDS.has(q)) continue;
    for (const [token, list] of index.tokens) {
      const s = token === q ? 100 : token.startsWith(q) ? 50 : q.length >= 4 && token.includes(q) ? 10 : 0;
      if (s) list.forEach((e) => add(e, s));
    }
  }
  return [...scored.entries()]
    .sort((a, b) => b[1].score - a[1].score || a[1].order - b[1].order)
    .map(([unicode, { label }]) => ({ unicode, label }));
}

/**
 * Suggestions for a title, best first. Synchronous: returns [] until the data
 * for the current app language has loaded (see loadEmojiData).
 */
export function getEmojiSuggestions(query: string, limit = 12, lang = appLanguage()): EmojiResult[] {
  const titleWords = words(query.trim());
  if (!titleWords.length) return [];

  const fromMap = [...keywordScores(titleWords, lang).entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([unicode]) => ({ unicode, label: '' }));
  let fromData = datasetResults(titleWords, datasets.get(lang));
  if (!fromData.length && lang !== 'en') fromData = datasetResults(titleWords, datasets.get('en'));

  const seen = new Set<string>();
  return [...fromMap, ...fromData].filter((r) => !seen.has(r.unicode) && seen.add(r.unicode)).slice(0, limit);
}

// --- on-device semantic fallback (iOS) --------------------------------------

interface EmojiSemanticPluginApi {
  suggest(options: { title: string; language: string }): Promise<{ emoji?: string }>;
}
const EmojiSemanticPlugin = registerPlugin<EmojiSemanticPluginApi>('EmojiSemanticPlugin');

/**
 * Asks Apple's on-device language model for the closest event type when the
 * keyword layers find nothing. iOS only; resolves undefined elsewhere.
 */
export async function getSemanticEmoji(title: string, lang = appLanguage()): Promise<string | undefined> {
  if (!Capacitor.isNativePlatform() || !title.trim()) return undefined;
  try {
    return (await EmojiSemanticPlugin.suggest({ title, language: lang })).emoji || undefined;
  } catch (err) {
    console.warn('[emojiSuggestions] semantic fallback failed', err);
    return undefined;
  }
}

/**
 * React hook: keyword suggestions, plus the semantic fallback when those are empty.
 * Re-renders when the language data finishes loading.
 */
export function useEmojiSuggestions(title: string, limit = 12): string[] {
  const [loaded, setLoaded] = useState(0);
  const [semantic, setSemantic] = useState<{ title: string; emoji?: string }>({ title: '' });
  const trimmed = title.trim();

  useEffect(() => {
    const bump = () => setLoaded((n) => n + 1);
    listeners.add(bump);
    return () => void listeners.delete(bump);
  }, []);

  const keywordResults = useMemo(
    () => (trimmed ? getEmojiSuggestions(trimmed, limit).map((r) => r.unicode) : []),
    // eslint-disable-next-line react-hooks/exhaustive-deps -- `loaded` re-runs once data arrives
    [trimmed, limit, loaded],
  );

  useEffect(() => {
    if (!trimmed || keywordResults.length) return;
    let cancelled = false;
    // ponytail: debounce so we don't call native on every keystroke
    const t = window.setTimeout(async () => {
      const emoji = await getSemanticEmoji(trimmed);
      if (!cancelled) setSemantic({ title: trimmed, emoji });
    }, 350);
    return () => {
      cancelled = true;
      window.clearTimeout(t);
    };
  }, [trimmed, keywordResults.length]);

  if (keywordResults.length) return keywordResults;
  return semantic.title === trimmed && semantic.emoji ? [semantic.emoji] : [];
}
