require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
  pod 'CapacitorActionSheet', :path => '../../node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorDialog', :path => '../../node_modules/@capacitor/dialog'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Pin UMP to v2.x for AdMob plugin compatibility
  pod 'GoogleUserMessagingPlatform', '~> 2.1'
end

target 'CountdownWidget' do
  platform :ios, '14.0'
  # Widgets typically don't require Capacitor pods. Add any widget-specific pods here if needed.
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Fix CordovaPlugins header search paths for CapacitorCordova framework
  installer.pods_project.targets.each do |target|
    if target.name == 'CordovaPlugins'
      target.build_configurations.each do |config|
        # Add header search paths for CapacitorCordova
        # Note: Framework file is CapacitorCordova.framework, but module_name is "Cordova"
        header_search_paths = config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
        
        # Add framework headers path (for when framework is built)
        unless header_search_paths.include?('CapacitorCordova.framework/Headers')
          config.build_settings['HEADER_SEARCH_PATHS'] = "#{header_search_paths} \"${PODS_CONFIGURATION_BUILD_DIR}/CapacitorCordova/CapacitorCordova.framework/Headers\""
        end
        
        # Add source headers path (for before framework is built)
        # This allows headers to be found during compilation even if framework isn't built yet
        # Use the actual path to node_modules where CapacitorCordova source is located
        capacitor_ios_path = File.expand_path('../../node_modules/@capacitor/ios', __dir__)
        source_header_path = "#{capacitor_ios_path}/CapacitorCordova/CapacitorCordova/Classes/Public"
        unless header_search_paths.include?(source_header_path)
          current_paths = config.build_settings['HEADER_SEARCH_PATHS']
          config.build_settings['HEADER_SEARCH_PATHS'] = "#{current_paths} \"#{source_header_path}\""
        end
      end
    end
  end
end
